name: Linux Build on Star

on:
  watch:
    types: [started]

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK and Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'

      - name: Build Linux executable
        run: |
          chmod +x bin/release-linux.sh
          bash bin/release-linux.sh

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: dist/*
          if-no-files-found: error
